// 力量训练内容库（对标训记）
// 包含：部位定义 + 核心动作详细信息（教学 / 安全 / 编程建议）

export const BODY_PARTS = [
  {
    id: 'chest',
    name: '胸',
    desc: '推类上肢大肌群，提升上半身厚度与力量',
  },
  {
    id: 'back',
    name: '背',
    desc: '拉类动作，打造背部宽度与厚度，改善体态',
  },
  {
    id: 'shoulders',
    name: '肩',
    desc: '三角肌前中后束，让上半身线条更立体',
  },
  {
    id: 'legs',
    name: '腿',
    desc: '深蹲、硬拉等大复合动作的主战场',
  },
  {
    id: 'glutes',
    name: '臀',
    desc: '髋伸展为主，提升爆发力与体态',
  },
  {
    id: 'arms',
    name: '手臂',
    desc: '二头、三头，让手臂更有围度与线条',
  },
  {
    id: 'core',
    name: '核心',
    desc: '稳定躯干，保护腰椎，提升力量传导效率',
  },
]

const baseExercise = ({
  id,
  name,
  aliases = [],
  bodyPart,
  subPart = null,
  difficulty,
  equipment,
  isUnilateral = false,
  primaryMuscles,
  secondaryMuscles = [],
  movementPattern,
  setup,
  execution,
  cues,
  breathing,
  tempo,
  rangeOfMotion,
  commonMistakes,
  safetyTips,
  regressions = [],
  progressions = [],
  recommendedRepRange,
  recommendedSets,
  weeklyFrequency,
  notesForWho,
  media = {},
}) => ({
  id,
  name,
  aliases,
  bodyPart,
  subPart,
  difficulty,
  equipment,
  isUnilateral,
  primaryMuscles,
  secondaryMuscles,
  movementPattern,
  setup,
  execution,
  cues,
  breathing,
  tempo,
  rangeOfMotion,
  commonMistakes,
  safetyTips,
  regressions,
  progressions,
  recommendedRepRange,
  recommendedSets,
  weeklyFrequency,
  notesForWho,
  media,
})

export const TRAINING_EXERCISES = [
  // ========= 胸 =========
  baseExercise({
    id: 'bench_press_barbell_flat',
    name: '杠铃卧推',
    aliases: ['卧推', '平板卧推'],
    bodyPart: 'chest',
    subPart: 'mid_chest',
    difficulty: 'intermediate',
    equipment: ['barbell', 'rack', 'bench'],
    isUnilateral: false,
    primaryMuscles: ['胸大肌（中束为主）'],
    secondaryMuscles: ['前三角肌', '肱三头肌'],
    movementPattern: 'horizontal_push',
    setup: [
      '躺在平板凳上，眼睛大致在杠铃正下方或略偏内侧',
      '双脚稳踩地面，脚掌完全着地，大腿与地面大致平行或略低',
      '肩胛骨向后下“夹紧”，背部形成自然的小拱桥，臀部始终贴凳',
      '握距略宽于肩（约 1.3~1.5 倍肩宽），手腕正对肘关节，上臂与身体约 45~60°',
      '从杠铃架上“推出”杠铃，让杠铃悬在胸骨中部正上方，手臂几乎伸直但不过分锁死',
    ],
    execution: [
      '吸气，保持肩胛骨后下夹紧，胸口抬起，想象“用胸去接杠铃”',
      '控制下放杠铃，沿略微弧形轨迹向胸骨下半部方向下降',
      '下放至胸前轻触或略上方，不要砸胸，也不要为“贴胸”而牺牲肩部舒适度',
      '呼气，用胸肌发力推起杠铃，想象“把地板推远”而不是“手举杠铃”',
      '在顶部保持肩胛稳定，不要耸肩或完全松掉背部拱桥',
    ],
    cues: [
      '肩胛往屁股口袋收（后下沉）',
      '胸顶杠，不要用肩抬杠',
      '下放慢、推起快（可控爆发）',
    ],
    breathing:
      '一般采用下放吸气、推起呼气；力量训练可在胸前短暂停顿后爆发推起再呼气',
    tempo: '2-1-1-0（下 2 秒、底部停 1 秒、推起 1 秒、顶部不停留）',
    rangeOfMotion:
      '下放至胸前轻触或略上方，肘角约 90° 左右；不要过度下沉导致肩前方不适',
    commonMistakes: [
      '肘外翻成 90°，肩关节压力过大',
      '下放过快借反弹，失去张力和控制',
      '手腕大幅后折，长期容易手腕疼',
      '耸肩发力，变成“肩推”而不是训练胸',
      '屁股离凳，为追求重量刻意抬臀',
    ],
    safetyTips: [
      '中大重量训练尽量有同伴保护或使用安全架',
      '肩有旧伤者可改用哑铃卧推或器械胸推，缩小活动范围',
      '不要在无人保护时被锁死在胸前位置',
    ],
    regressions: ['push_up', 'chest_press_machine'],
    progressions: ['bench_press_barbell_pause', 'bench_press_barbell_close_grip'],
    recommendedRepRange: [
      { goal: 'strength', reps: [3, 5] },
      { goal: 'hypertrophy', reps: [6, 12] },
      { goal: 'endurance', reps: [12, 20] },
    ],
    recommendedSets: [
      { level: 'beginner', sets: [3, 4] },
      { level: 'intermediate', sets: [4, 6] },
      { level: 'advanced', sets: [5, 8] },
    ],
    weeklyFrequency: '每周练胸 2~3 次时，卧推可安排在其中 1~2 次作为主动作',
    notesForWho: {
      recommendedFor: [
        '希望提升推举力量（卧推一 RM）的人',
        '希望增加上半身厚度、整体胸肌发展的练习者',
      ],
      avoidIf: [
        '急性肩袖损伤、前肩疼痛明显者',
        '胸大肌或胸骨附近有近期拉伤史的人',
      ],
    },
    media: {
      coverImage: '/media/training/bench_press_barbell_flat.png',
    },
  }),
  baseExercise({
    id: 'push_up',
    name: '俯卧撑',
    aliases: ['伏地挺身'],
    bodyPart: 'chest',
    subPart: 'mid_chest',
    difficulty: 'beginner',
    equipment: ['bodyweight'],
    isUnilateral: false,
    primaryMuscles: ['胸大肌'],
    secondaryMuscles: ['前三角肌', '肱三头肌', '核心稳定肌群'],
    movementPattern: 'horizontal_push',
    setup: [
      '双手略宽于肩撑地，手指朝前或略外旋，手腕大致在肩正下方',
      '双脚并拢或与髋同宽支撑，脚尖点地',
      '身体从头到脚成一条直线，收紧臀部和腹部，避免塌腰或翘臀',
    ],
    execution: [
      '吸气，弯曲肘关节缓慢下放身体，胸部朝地面接近',
      '下放时肘部朝斜后方约 30~45°，不要完全外张成“十字架”',
      '下放至胸部接近地面或鼻子接近地面，仍保持躯干一条直线',
      '呼气，用胸和手臂发力推回起始位置，手臂几乎伸直但不过分锁死',
    ],
    cues: [
      '身体像一块“硬木板”，从头到脚一条线',
      '胸去找地面，而不是头去找地面',
      '手肘略向身体靠近，不要完全外张',
    ],
    breathing: '下放吸气，推起呼气；节奏可均匀控制在 2-1-1-0',
    tempo: '2-0-1-0（下 2 秒、推 1 秒）',
    rangeOfMotion: '尽量做到胸部接近地面且保持身体一条直线，但不过度塌腰',
    commonMistakes: [
      '塌腰或“蛇形”起身，核心失去张力',
      '屁股翘得过高，变成“肩推”而不是胸推',
      '头往前伸，脖子紧张，实际胸部下放不足',
    ],
    safetyTips: [
      '手腕敏感者可用俯卧撑支架或握哑铃，减小腕关节伸展角度',
      '如腰部不适，优先确保核心收紧，再决定是否缩短活动范围',
    ],
    regressions: ['push_up_knee'],
    progressions: ['push_up_decline', 'push_up_weighted'],
    recommendedRepRange: [
      { goal: 'hypertrophy', reps: [8, 20] },
      { goal: 'endurance', reps: [15, 30] },
    ],
    recommendedSets: [
      { level: 'beginner', sets: [2, 4] },
      { level: 'intermediate', sets: [3, 5] },
      { level: 'advanced', sets: [4, 6] },
    ],
    weeklyFrequency: '每周 2~4 次，可作为家庭训练或热身中的推类动作',
    notesForWho: {
      recommendedFor: ['完全新手', '无器械环境下训练的人'],
      avoidIf: ['手腕急性疼痛、肩部无法承受撑地体重者'],
    },
    media: {
      coverImage: '/media/training/push_up.png',
    },
  }),

  // ========= 腿 / 臀 =========
  baseExercise({
    id: 'squat_barbell_back',
    name: '杠铃深蹲',
    aliases: ['深蹲', '后蹲'],
    bodyPart: 'legs',
    subPart: 'quads_glutes',
    difficulty: 'intermediate',
    equipment: ['barbell', 'rack'],
    isUnilateral: false,
    primaryMuscles: ['股四头肌', '臀大肌'],
    secondaryMuscles: ['腘绳肌', '竖脊肌', '小腿肌群'],
    movementPattern: 'squat',
    setup: [
      '杠铃架高度略低于肩，走到杠下让杠铃落在斜方肌上方而不是颈椎上',
      '双手略宽于肩抓杠，肩胛后缩夹紧，胸口抬起',
      '稳住杠铃后从架上“抬起”，后退 1~2 小步站稳',
      '双脚与肩同宽或略宽，脚尖略向外约 15~30°，根据髋部舒适度微调',
    ],
    execution: [
      '深吸气，收紧核心，想象腰部被束腰带牢牢固定',
      '同时屈髋屈膝向下，下蹲时膝盖大致朝脚尖方向，避免明显内扣',
      '躯干略前倾但保持脊柱中立，不要弓腰驼背',
      '下蹲至大腿至少与地面平行（或在自己灵活舒适的前提下更深）',
      '在底部短暂停顿保持张力，随后脚掌均匀发力（尤其脚后跟和脚掌外侧）站起',
      '站起时想象“向地板用力踩下去”，不是“腰去抬杠”',
    ],
    cues: [
      '像坐到身后的一把椅子上',
      '脚掌三点着地：大脚趾根、小脚趾根、脚跟',
      '膝盖朝脚尖方向跟着脚走',
    ],
    breathing:
      '每次下蹲前吸气并收紧核心，下蹲与起立过程中尽量保持腹内压，起立到安全位置再呼气',
    tempo: '2-1-1-0 或 3-1-1-0（控制下放，底部短暂停顿）',
    rangeOfMotion:
      '建议至少蹲至大腿与地面平行，根据髋踝灵活度和腰膝情况决定是否更深',
    commonMistakes: [
      '塌腰或驼背，腰椎过度屈曲',
      '膝盖明显内扣，尤其是在起立时',
      '重心完全在脚尖，脚跟抬起',
      '下蹲过快在底部“弹弹簧”，失去控制',
    ],
    safetyTips: [
      '中大重量必须使用护杠或安全架，避免被压在底部无法起身',
      '有膝盖既往严重损伤史者，应在专业指导下逐渐尝试',
      '初学者可先从徒手深蹲、 goblet 深蹲开始',
    ],
    regressions: ['goblet_squat', 'bodyweight_squat'],
    progressions: ['front_squat_barbell', 'squat_barbell_pause'],
    recommendedRepRange: [
      { goal: 'strength', reps: [3, 5] },
      { goal: 'hypertrophy', reps: [6, 10] },
    ],
    recommendedSets: [
      { level: 'beginner', sets: [3, 4] },
      { level: 'intermediate', sets: [4, 6] },
      { level: 'advanced', sets: [5, 8] },
    ],
    weeklyFrequency: '每周 1~2 次作为腿部或下肢训练的核心大动作',
    notesForWho: {
      recommendedFor: ['希望提升下肢综合力量与肌肉量的练习者'],
      avoidIf: ['急性腰椎损伤、膝关节急性疼痛尚未恢复者'],
    },
    media: {
      coverImage: '/media/training/squat_barbell_back.png',
    },
  }),
  baseExercise({
    id: 'deadlift_barbell_conventional',
    name: '杠铃硬拉',
    aliases: ['硬拉'],
    bodyPart: 'legs',
    subPart: 'posterior_chain',
    difficulty: 'intermediate',
    equipment: ['barbell'],
    isUnilateral: false,
    primaryMuscles: ['臀大肌', '腘绳肌'],
    secondaryMuscles: ['竖脊肌', '斜方肌', '前臂握力'],
    movementPattern: 'hip_hinge',
    setup: [
      '站在杠铃中间，脚掌在杠铃下方，大致让杠铃投影在鞋带中间',
      '脚与髋同宽或略窄，脚尖略微外旋',
      '屈髋屈膝向下抓杠，双手在小腿外侧，握距略宽于肩',
      '在抓杠前先挺胸、肩胛略后缩，保持背部平直',
    ],
    execution: [
      '深吸气，收紧核心，想象“把腋下夹紧”',
      '同时用脚向下踩地、臀向前推，带动杠铃沿腿部向上滑行',
      '整个过程中保持脊柱中立，避免弓背或过度仰腰',
      '站直时髋与膝完全伸直，臀部夹紧，下背仍保持中立',
      '反向过程是屈髋为主，先把臀部向后推，让杠铃贴着大腿滑下，再弯膝直至放回地面',
    ],
    cues: [
      '像把地面踩穿',
      '杠铃贴腿走，膝盖往后让路',
      '整块躯干抬起，而不是只用腰去拎杠铃',
    ],
    breathing:
      '每次起拉前深吸气收紧核心，起拉过程中保持腹内压，站直后再呼气',
    tempo: '1-0-1-1（起拉可稍快，下放控制，底部可短停）',
    rangeOfMotion:
      '标准做法从地面拉起至站直，初期如柔韧度不足可从增高垫（rack pull）开始',
    commonMistakes: [
      '起拉时背部弓起，完全靠腰顶起重量',
      '离心下放阶段直接“丢杠”，不控制',
      '杠铃离身太远，形成长杠杆，腰部压力巨增',
    ],
    safetyTips: [
      '不要用极度疲劳状态去挑战大重量硬拉',
      '有严重腰椎病史者务必在专业教练指导下训练',
      '避免在硬质地面赤脚拉非常大重量（可用硬拉鞋或平底鞋）',
    ],
    regressions: ['romanian_deadlift', 'rack_pull'],
    progressions: ['deadlift_barbell_deficit', 'deadlift_barbell_snatch_grip'],
    recommendedRepRange: [
      { goal: 'strength', reps: [3, 5] },
      { goal: 'hypertrophy', reps: [5, 8] },
    ],
    recommendedSets: [
      { level: 'beginner', sets: [2, 3] },
      { level: 'intermediate', sets: [3, 5] },
      { level: 'advanced', sets: [4, 6] },
    ],
    weeklyFrequency: '建议每周 1 次大重量硬拉，另可搭配 1 次轻量罗马尼亚硬拉',
    notesForWho: {
      recommendedFor: ['希望整体提升力量、增加臀腿后侧肌群的人'],
      avoidIf: ['腰椎急性损伤期、无法在不痛前提下保持中立脊柱者'],
    },
    media: {
      coverImage: '/media/training/deadlift_barbell_conventional.png',
    },
  }),

  // ========= 背 =========
  baseExercise({
    id: 'row_barbell_bent_over',
    name: '杠铃俯身划船',
    aliases: ['俯身划船', '杠铃划船'],
    bodyPart: 'back',
    subPart: 'mid_back',
    difficulty: 'intermediate',
    equipment: ['barbell'],
    isUnilateral: false,
    primaryMuscles: ['背阔肌', '菱形肌'],
    secondaryMuscles: ['后束三角肌', '竖脊肌', '肱二头肌'],
    movementPattern: 'horizontal_pull',
    setup: [
      '双脚与肩同宽站立，双手略宽于肩正握杠铃',
      '屈髋向后折叠，保持背部平直，躯干大致与地面成 30~45° 角',
      '膝盖略微弯曲，不要锁死',
    ],
    execution: [
      '先让杠铃在手臂自然下垂位置悬空，肩胛保持稳定不过度耸肩',
      '吸气，向后向内“夹”肩胛，将杠铃朝肚脐或下胸方向拉近',
      '拉起时肘部贴近身体两侧，想象用“后背发力拉”而不是手臂用力弯曲',
      '在最高点短暂停顿 1 秒，感受肩胛挤压与背部收缩',
      '呼气，控制下放杠铃回到手臂伸直位置',
    ],
    cues: [
      '胸口向前顶，背要挺',
      '用背“拖”杠铃，而不是用手“提”杠铃',
      '肘向后划，不是向外甩',
    ],
    breathing: '拉起时吸气或屏气，下放时呼气，可根据重量和习惯微调',
    tempo: '2-1-2-0（上 1~2 秒、顶峰停 1 秒、下放 2 秒）',
    rangeOfMotion: '拉到杠铃接近腹部 / 下胸，整个过程都保持肩胛受控',
    commonMistakes: [
      '重量太大导致身体剧烈晃动，用惯性甩杠',
      '弓背或抬头过高，颈椎、腰椎受压',
      '完全用手臂发力，背部感觉不到收缩',
    ],
    safetyTips: [
      '下背有问题者可考虑改为胸托划船或坐姿划船',
      '避免在极度疲劳时继续用大重量硬扯',
    ],
    regressions: ['row_dumbbell_one_arm', 'row_cable_seated'],
    progressions: ['row_barbell_pendlay'],
    recommendedRepRange: [
      { goal: 'hypertrophy', reps: [6, 12] },
      { goal: 'strength', reps: [4, 6] },
    ],
    recommendedSets: [
      { level: 'beginner', sets: [3, 4] },
      { level: 'intermediate', sets: [4, 5] },
      { level: 'advanced', sets: [4, 6] },
    ],
    weeklyFrequency: '每周 2~3 次背部训练中可安排 1~2 次作为水平拉主动作',
    notesForWho: {
      recommendedFor: ['希望提升背部厚度和整体拉力的人'],
      avoidIf: ['急性下背痛、无法保持俯身姿势者'],
    },
    media: {
      coverImage: '/media/training/row_barbell_bent_over.png',
    },
  }),
  baseExercise({
    id: 'lat_pulldown_wide_grip',
    name: '宽握高位下拉',
    aliases: ['高位下拉'],
    bodyPart: 'back',
    subPart: 'lats',
    difficulty: 'beginner',
    equipment: ['machine', 'cable'],
    isUnilateral: false,
    primaryMuscles: ['背阔肌'],
    secondaryMuscles: ['肱二头肌', '后束三角肌'],
    movementPattern: 'vertical_pull',
    setup: [
      '坐在高位下拉器械上，大腿固定垫压住大腿根部',
      '双手宽握横杠，手心朝前，握距略宽于肩 1.5 倍左右',
      '微微后仰约 10~20°，胸口抬起，腰背保持自然曲线',
    ],
    execution: [
      '先略向下带动肩胛，感受背阔肌启动，而不是一开始就弯肘拉',
      '继续下拉横杠至接近锁骨或上胸位置，肘部朝下略向身后',
      '下拉过程中保持胸口抬起，避免含胸驼背',
      '在最低点短暂停顿 1 秒，感受背阔肌收缩',
      '控制横杠回位，避免突然弹起，保持背部张力',
    ],
    cues: [
      '想象“用腋下夹东西”拉下横杠',
      '手只是“挂着杠”，主力来自背部',
    ],
    breathing: '下拉时吸气或屏气，回放时呼气，根据重量与个人习惯调整',
    tempo: '2-1-2-0',
    rangeOfMotion: '尽量拉到下巴以下或锁骨附近，再控制回到接近顶端但不过度耸肩',
    commonMistakes: [
      '身体大幅后仰“荡秋千”，靠惯性拉',
      '含胸、肩膀前缩，背阔肌参与不足',
      '把横杠拉到很低甚至砸到腹部，超出舒适肩关节范围',
    ],
    safetyTips: [
      '避免用极大重量猛拉导致肩部不适',
      '有肩关节撞击综合征史者应缩短活动范围或减小重量',
    ],
    regressions: ['row_cable_seated'],
    progressions: ['pull_up_bodyweight'],
    recommendedRepRange: [
      { goal: 'hypertrophy', reps: [8, 15] },
      { goal: 'endurance', reps: [12, 20] },
    ],
    recommendedSets: [
      { level: 'beginner', sets: [3, 4] },
      { level: 'intermediate', sets: [3, 5] },
      { level: 'advanced', sets: [4, 6] },
    ],
    weeklyFrequency: '可在每次背部训练中安排 1 次作为垂直拉主动作',
    notesForWho: {
      recommendedFor: ['无法完成标准引体但想训练背阔肌的人'],
      avoidIf: ['肩部外展外旋时明显疼痛者'],
    },
    media: {
      coverImage: '/media/training/lat_pulldown_wide_grip.png',
    },
  }),

  // ========= 肩 =========
  baseExercise({
    id: 'overhead_press_barbell',
    name: '杠铃推举',
    aliases: ['站姿杠铃推举', '肩上推举'],
    bodyPart: 'shoulders',
    subPart: 'front_middle_delts',
    difficulty: 'intermediate',
    equipment: ['barbell', 'rack'],
    isUnilateral: false,
    primaryMuscles: ['三角肌前束', '三角肌中束'],
    secondaryMuscles: ['肱三头肌', '斜方肌上部', '核心稳定肌群'],
    movementPattern: 'vertical_push',
    setup: [
      '杠铃架高度大致在胸上方，站在杠前，双手略宽于肩宽正握杠铃',
      '将杠铃置于锁骨上方 / 肩前部位，肘略在杠铃前方',
      '双脚与肩同宽站立，收紧臀部与核心，保持躯干稳定',
    ],
    execution: [
      '深吸气，收紧核心与臀部，避免弓腰',
      '向上推举杠铃，略从下巴前方绕过，最终停在耳朵略后上方位置',
      '整个过程保持躯干稳固，不要后仰用腰硬顶',
      '控制下放杠铃至肩前原位，肘略在杠铃前方',
    ],
    cues: [
      '屁股夹紧，肋骨向下收，不要“挺胸塌腰”',
      '把身体推到杠铃下面，而不仅是把杠铃往前推',
    ],
    breathing:
      '起推前吸气并收紧核心，推举过程中保持张力，推到顶端后再呼气（或在安全位置轻微呼气）',
    tempo: '1-0-2-0（上快下慢）',
    rangeOfMotion: '从肩前高度推至手臂接近完全伸直，杠铃在耳朵略后上方',
    commonMistakes: [
      '大幅后仰变成“斜板卧推”，腰椎受压',
      '手肘完全在杠铃后方，发力路径不顺',
      '下放过快，失去控制且肩部受压大',
    ],
    safetyTips: [
      '有腰椎问题者可改为坐姿或靠墙推举，减少下背参与',
      '肩关节疼痛者需减小重量与活动范围，或改为哑铃推举',
    ],
    regressions: ['shoulder_press_dumbbell_seated'],
    progressions: ['push_press', 'overhead_press_barbell_behind_neck'],
    recommendedRepRange: [
      { goal: 'strength', reps: [3, 6] },
      { goal: 'hypertrophy', reps: [6, 12] },
    ],
    recommendedSets: [
      { level: 'beginner', sets: [3, 4] },
      { level: 'intermediate', sets: [4, 6] },
      { level: 'advanced', sets: [5, 6] },
    ],
    weeklyFrequency: '每周 1~2 次作为肩部或上肢推举主动作',
    notesForWho: {
      recommendedFor: ['希望整体提升上肢推举力量与肩部围度的人'],
      avoidIf: ['举过头时明显疼痛或肩关节活动严重受限者'],
    },
    media: {
      coverImage: '/media/training/overhead_press_barbell.png',
    },
  }),
  baseExercise({
    id: 'lateral_raise_dumbbell',
    name: '哑铃侧平举',
    aliases: ['侧平举'],
    bodyPart: 'shoulders',
    subPart: 'middle_delts',
    difficulty: 'beginner',
    equipment: ['dumbbell'],
    isUnilateral: false,
    primaryMuscles: ['三角肌中束'],
    secondaryMuscles: ['上斜方肌（如耸肩过多）'],
    movementPattern: 'isolation',
    setup: [
      '站立或坐姿，双手各持一只哑铃于身体两侧，手心可略朝内',
      '微屈肘，肩放松下沉，胸略抬',
    ],
    execution: [
      '吸气，收紧核心，保持躯干稳定不晃动',
      '以肩关节外展为主，将哑铃向身体两侧抬起至略低于肩高（约与地面平行）',
      '整个过程中肘略高于手或同一水平线，手腕不过度上翘',
      '在最高点短暂停顿 1 秒，感受三角肌中束发力',
      '控制下放哑铃回到身体两侧，不要完全失去张力砸到底',
    ],
    cues: [
      '想象用“手背带动小指往上画弧”',
      '身体像被墙粘住，只允许手臂动',
    ],
    breathing: '抬起时呼气，下放时吸气，保持节奏连贯',
    tempo: '2-1-2-0',
    rangeOfMotion: '从大腿旁侧抬至略低于肩高，避免抬得过高导致肩关节不适',
    commonMistakes: [
      '重量太大用腰和惯性甩哑铃',
      '宽耸肩，斜方肌抢占主要发力',
      '肘过度伸直锁死，增加肘关节压力',
    ],
    safetyTips: [
      '选择可控重量，优先感受目标肌肉而非追求重量',
      '肩部已有伤病者可缩小活动范围并减轻重量',
    ],
    regressions: [],
    progressions: ['lateral_raise_cable'],
    recommendedRepRange: [
      { goal: 'hypertrophy', reps: [10, 20] },
    ],
    recommendedSets: [
      { level: 'beginner', sets: [2, 3] },
      { level: 'intermediate', sets: [3, 4] },
      { level: 'advanced', sets: [3, 5] },
    ],
    weeklyFrequency: '每周肩部训练中可安排 2~3 次小重量高次数练习',
    notesForWho: {
      recommendedFor: ['想要更宽肩线条的人'],
      avoidIf: ['侧平举时肩关节外侧锐痛明显者'],
    },
    media: {
      coverImage: '/media/training/lateral_raise_dumbbell.png',
    },
  }),

  // ========= 手臂 =========
  baseExercise({
    id: 'curl_dumbbell',
    name: '哑铃弯举',
    aliases: ['弯举', '二头弯举'],
    bodyPart: 'arms',
    subPart: 'biceps',
    difficulty: 'beginner',
    equipment: ['dumbbell'],
    isUnilateral: false,
    primaryMuscles: ['肱二头肌'],
    secondaryMuscles: ['肱肌', '前臂屈肌群'],
    movementPattern: 'elbow_flexion',
    setup: [
      '站立或坐姿，双手各持一只哑铃自然下垂，手心朝前或略朝内',
      '肩部放松，胸略抬，核心轻度收紧',
    ],
    execution: [
      '保持上臂基本垂直于地面不前后摆动',
      '屈肘将哑铃向肩部弯举，过程中手心可逐渐旋转朝向自己',
      '在最高点肘关节接近完全屈曲，但不要用前臂撞到肱二头肌来“卡住”',
      '短暂停顿 1 秒感受二头肌收缩，然后控制下放回起始位置',
    ],
    cues: [
      '想象用“肘部作为轴”，只让前臂转动',
      '上臂像被黏在身体两侧',
    ],
    breathing: '弯举时呼气，下放时吸气，节奏稳定',
    tempo: '2-1-2-0',
    rangeOfMotion: '从手臂自然下垂到最大舒适屈曲，始终保持肌肉张力',
    commonMistakes: [
      '身体后仰借力，变成“腰部甩铃”',
      '耸肩、肩和肘一起向前抬起',
      '下放过快，完全失控',
    ],
    safetyTips: [
      '不要用爆发性甩动大重量，预防肱二头肌肌腱拉伤',
      '肘关节不适时可改为锤式弯举或器械弯举',
    ],
    regressions: [],
    progressions: ['curl_barbell_strict'],
    recommendedRepRange: [
      { goal: 'hypertrophy', reps: [8, 15] },
    ],
    recommendedSets: [
      { level: 'beginner', sets: [2, 3] },
      { level: 'intermediate', sets: [3, 4] },
      { level: 'advanced', sets: [3, 5] },
    ],
    weeklyFrequency: '每周 1~3 次作为拉练或手臂专项中的辅助动作',
    notesForWho: {
      recommendedFor: ['希望提升手臂围度与线条的人'],
      avoidIf: ['肘窝部位有明显疼痛或旧伤者'],
    },
    media: {
      coverImage: '/media/training/curl_dumbbell.png',
    },
  }),

  // ========= 核心 =========
  baseExercise({
    id: 'plank',
    name: '平板支撑',
    aliases: [],
    bodyPart: 'core',
    subPart: 'anti_extension',
    difficulty: 'beginner',
    equipment: ['bodyweight'],
    isUnilateral: false,
    primaryMuscles: ['腹直肌', '腹横肌'],
    secondaryMuscles: ['臀大肌', '竖脊肌'],
    movementPattern: 'isometric',
    setup: [
      '俯卧在地面上，以前臂和脚尖支撑身体',
      '肘关节大致在肩膀正下方，前臂与身体平行或略向内收',
      '收紧臀部和腹部，让身体从头到脚成一条直线',
    ],
    execution: [
      '保持正常呼吸，不要长时间屏气憋闷',
      '注意维持躯干稳定，避免塌腰或屁股翘高',
      '在可控时间内（如 20~60 秒）保持姿势不变',
    ],
    cues: [
      '想象肚脐向脊柱方向轻轻收紧',
      '脚跟向后推，头顶向前伸，身体拉长',
    ],
    breathing: '全程均匀呼吸，不要刻意憋气',
    tempo: '保持等长收缩，根据计时控制',
    rangeOfMotion: '保持身体一条直线，无大幅度晃动',
    commonMistakes: [
      '腰部明显塌下，腰椎压力大',
      '臀部抬得太高，失去核心训练价值',
      '耸肩、颈部紧绷',
    ],
    safetyTips: [
      '初学者可从膝撑版本开始，逐渐过渡到脚尖支撑',
      '如出现下背疼痛，应立即停止并调整动作或改用其他核心练习',
    ],
    regressions: [],
    progressions: ['plank_weighted', 'plank_one_leg'],
    recommendedRepRange: [
      { goal: 'endurance', reps: [20, 60] }, // 秒数
    ],
    recommendedSets: [
      { level: 'beginner', sets: [2, 3] },
      { level: 'intermediate', sets: [3, 4] },
      { level: 'advanced', sets: [3, 5] },
    ],
    weeklyFrequency: '每周 2~4 次作为基础核心稳定训练',
    notesForWho: {
      recommendedFor: ['大多数人，尤其是久坐人群和力量训练新手'],
      avoidIf: ['急性腰椎疼痛、无法维持任何前支撑姿势者'],
    },
    media: {
      coverImage: '/media/training/plank.png',
    },
  }),
  // ========= 更多胸部 =========
  baseExercise({
    id: 'bench_press_dumbbell_incline',
    name: '上斜哑铃卧推',
    aliases: ['上斜卧推（哑铃）'],
    bodyPart: 'chest',
    subPart: 'upper_chest',
    difficulty: 'intermediate',
    equipment: ['dumbbell', 'bench'],
    isUnilateral: false,
    primaryMuscles: ['胸大肌上束'],
    secondaryMuscles: ['前三角肌', '肱三头肌'],
    movementPattern: 'horizontal_push',
    setup: [
      '将卧推凳调到约 30°~45° 上斜角度，角度越大前三角肌参与越多',
      '坐在凳子上，把哑铃放在大腿上，仰卧时借助大腿将哑铃送至胸前',
      '手心相对或略朝前，手腕中立，肩胛后缩下沉，保持胸口抬起',
    ],
    execution: [
      '吸气，控制下放哑铃，前臂大致垂直地面，下放轨迹朝上胸或锁骨下方',
      '下放至上臂略低于水平或哑铃接近胸上部，保持肩胛稳定不耸肩',
      '呼气，用胸肌发力将哑铃沿相同轨迹推起，顶端可略靠近但不过分相撞',
    ],
    cues: [
      '想象“用上胸夹爆哑铃”',
      '肘略向身体靠近，不要变成高位推举',
    ],
    breathing: '下放吸气，推起呼气；接近力竭组可在底部略停顿再爆发推起',
    tempo: '2-0-1-0/2-1-1-0',
    rangeOfMotion: '下放至胸上部舒适位置，不出现肩前锐痛为前提下尽量全程',
    commonMistakes: [
      '凳子角度过高，变成肩推为主',
      '在顶部完全相撞，借惯性弹起下一次',
      '耸肩、含胸，导致肩前部压力大',
    ],
    safetyTips: [
      '重重量时上凳和下凳要控制好哑铃轨迹，防止肩部被打开过度',
      '有肩关节撞击史者可缩短下放范围并减小斜板角度',
    ],
    regressions: ['push_up_decline', 'chest_press_machine'],
    progressions: ['bench_press_barbell_incline'],
    recommendedRepRange: [
      { goal: 'hypertrophy', reps: [6, 12] },
    ],
    recommendedSets: [
      { level: 'beginner', sets: [3, 4] },
      { level: 'intermediate', sets: [3, 5] },
      { level: 'advanced', sets: [4, 5] },
    ],
    weeklyFrequency: '每周胸部训练中可安排 1~2 次，特别适合想强调上胸的人',
    notesForWho: {
      recommendedFor: ['想改善“胸肌下垂”、提升上胸饱满度的人'],
      avoidIf: ['上举动作即刻诱发肩前或肩顶部疼痛者'],
    },
    media: {
      coverImage: '/media/training/bench_press_dumbbell_incline.png',
    },
  }),
  baseExercise({
    id: 'chest_fly_cable',
    name: '拉力器夹胸',
    aliases: ['夹胸', '绳索夹胸'],
    bodyPart: 'chest',
    subPart: 'mid_chest',
    difficulty: 'beginner',
    equipment: ['cable'],
    isUnilateral: false,
    primaryMuscles: ['胸大肌'],
    secondaryMuscles: ['前三角肌'],
    movementPattern: 'isolation',
    setup: [
      '站在双边拉力器中间，手柄高度略高于肩或与肩同高',
      '双脚前后站稳，躯干略前倾，胸口抬起',
      '双手各握一侧手柄，手肘略弯，手臂略向两侧张开',
    ],
    execution: [
      '吸气，感受胸部被拉伸，不要让肩膀完全被向后拉走',
      '呼气时以“抱树”的轨迹将双手在身体前方合拢，约胸前或略下位置',
      '在夹紧位置短暂停顿 1 秒，刻意挤压胸肌',
      '控制手臂慢慢回到起始被拉伸的位置，保持肘部弧线不变',
    ],
    cues: [
      '想象“用手肘夹东西”，让胸发力，不是用手硬拉',
      '胸始终朝前，肩不要被拉得向前圆背',
    ],
    breathing: '夹紧时呼气，回到拉伸位时吸气',
    tempo: '2-1-2-0',
    rangeOfMotion: '在不牺牲肩部舒适度的前提下，让胸肌有明显拉伸与收缩',
    commonMistakes: [
      '重量过大，身体前后晃动严重',
      '手肘角度在过程中变化太多，变成推而不是飞鸟',
      '含胸驼背，胸肌参与度降低',
    ],
    safetyTips: [
      '不要用特别大重量，优先以感觉胸部发力为主',
      '肩前已有伤者建议从更轻重量和更小活动范围开始',
    ],
    regressions: ['chest_fly_dumbbell'],
    progressions: [],
    recommendedRepRange: [
      { goal: 'hypertrophy', reps: [10, 20] },
    ],
    recommendedSets: [
      { level: 'beginner', sets: [2, 3] },
      { level: 'intermediate', sets: [3, 4] },
      { level: 'advanced', sets: [3, 5] },
    ],
    weeklyFrequency: '每周 1~3 次，常作为胸部训练的中后段“泵感”动作',
    notesForWho: {
      recommendedFor: ['希望增加胸肌“线条感”和内侧挤压感的人'],
      avoidIf: ['肩外展外旋明显诱发疼痛者'],
    },
    media: {
      coverImage: '/media/training/chest_fly_cable.png',
    },
  }),

  // ========= 更多腿 / 臀 =========
  baseExercise({
    id: 'goblet_squat',
    name: '高举壶铃/哑铃深蹲',
    aliases: ['抱铃深蹲'],
    bodyPart: 'legs',
    subPart: 'quads_glutes',
    difficulty: 'beginner',
    equipment: ['dumbbell', 'kettlebell'],
    isUnilateral: false,
    primaryMuscles: ['股四头肌', '臀大肌'],
    secondaryMuscles: ['腘绳肌', '竖脊肌'],
    movementPattern: 'squat',
    setup: [
      '双手托住一只哑铃或壶铃，贴近胸前或下巴下方',
      '双脚与肩同宽或略宽，脚尖略向外，胸口抬起',
    ],
    execution: [
      '吸气，屈髋屈膝下蹲，保持壶铃贴近身体不晃动',
      '下蹲时膝盖大致朝脚尖方向，重心在脚掌中后部',
      '蹲至大腿平行或略低，保持躯干相对直立',
      '呼气，脚掌均匀发力回到站立姿势',
    ],
    cues: [
      '想象把身体坐到两腿之间，而不是单纯往后坐',
      '壶铃始终贴近身体，好像“抱着一个大保温杯”',
    ],
    breathing: '下蹲吸气，起立呼气',
    tempo: '2-1-1-0',
    rangeOfMotion: '根据踝髋灵活度，在不塌腰不疼痛前提下尽量下蹲',
    commonMistakes: [
      '上身过度前倾，变成“弯腰抱铃”',
      '膝盖严重内扣',
      '抱铃离身体太远，腰部压力增大',
    ],
    safetyTips: [
      '作为深蹲入门动作非常友好，但也要避免急速下蹲和弹起',
    ],
    regressions: ['bodyweight_squat'],
    progressions: ['squat_barbell_back'],
    recommendedRepRange: [
      { goal: 'hypertrophy', reps: [8, 15] },
      { goal: 'endurance', reps: [15, 20] },
    ],
    recommendedSets: [
      { level: 'beginner', sets: [2, 4] },
      { level: 'intermediate', sets: [3, 4] },
      { level: 'advanced', sets: [3, 5] },
    ],
    weeklyFrequency: '每周 2~3 次，可作为腿部训练热身或主力动作',
    notesForWho: {
      recommendedFor: ['深蹲新手', '家庭训练用户'],
      avoidIf: ['膝盖弯曲即刻痛的人需要先排查原因再练'],
    },
    media: {
      coverImage: '/media/training/goblet_squat.png',
    },
  }),
  baseExercise({
    id: 'hip_thrust_barbell',
    name: '杠铃臀推',
    aliases: ['臀推'],
    bodyPart: 'glutes',
    subPart: 'glute_max',
    difficulty: 'intermediate',
    equipment: ['barbell', 'bench'],
    isUnilateral: false,
    primaryMuscles: ['臀大肌'],
    secondaryMuscles: ['腘绳肌', '竖脊肌'],
    movementPattern: 'hip_extension',
    setup: [
      '上背（肩胛下缘附近）靠在凳子边缘，双脚踩地，脚距略宽于髋',
      '在髋部放置包好保护垫的杠铃，双手固定杠铃防止滚动',
    ],
    execution: [
      '从臀部下沉姿势开始，髋关节屈曲，杠铃靠近地面',
      '吸气，然后用臀部发力向上推髋，让身体从膝到肩成一条直线',
      '在顶点刻意夹臀，停顿 1 秒，感受臀部收缩',
      '控制下放髋部，回到起始位置，腰椎始终保持中立，不要过度塌腰',
    ],
    cues: [
      '脚跟发力，想象用“屁股顶高杠铃”',
      '顶点时肋骨不要外翻，避免用腰顶',
    ],
    breathing: '向上顶髋时呼气，下放时吸气；大重量可在起顶前先吸气再屏气短暂起顶',
    tempo: '1-1-2-0',
    rangeOfMotion: '从髋部明显下降到接近地面，再推到身体成直线；不过度过伸腰背',
    commonMistakes: [
      '用腰去拱而不是用臀部发力',
      '双脚位置太远或太近，导致大腿前侧或膝盖不适',
    ],
    safetyTips: [
      '杠铃一定要有软垫，避免压髋部软组织',
      '有腰椎敏感史者要控制顶点腰椎位置，避免过伸',
    ],
    regressions: ['glute_bridge_bodyweight'],
    progressions: ['hip_thrust_barbell_single_leg'],
    recommendedRepRange: [
      { goal: 'hypertrophy', reps: [8, 15] },
      { goal: 'strength', reps: [5, 8] },
    ],
    recommendedSets: [
      { level: 'beginner', sets: [2, 3] },
      { level: 'intermediate', sets: [3, 5] },
      { level: 'advanced', sets: [4, 6] },
    ],
    weeklyFrequency: '每周 1~3 次臀部专项训练中使用，注意和硬拉等动作统筹恢复',
    notesForWho: {
      recommendedFor: ['希望提升臀部围度、爆发力的人'],
      avoidIf: ['髋关节或腰椎屈伸时即刻疼痛者'],
    },
    media: {
      coverImage: '/media/training/hip_thrust_barbell.png',
    },
  }),

  // ========= 更多背部 =========
  baseExercise({
    id: 'row_cable_seated',
    name: '坐姿划船（拉力器）',
    aliases: ['坐姿划船'],
    bodyPart: 'back',
    subPart: 'mid_back',
    difficulty: 'beginner',
    equipment: ['machine', 'cable'],
    isUnilateral: false,
    primaryMuscles: ['背阔肌', '菱形肌'],
    secondaryMuscles: ['后束三角肌', '肱二头肌'],
    movementPattern: 'horizontal_pull',
    setup: [
      '坐在坐姿划船器上，双脚踩在踏板，膝盖略弯',
      '双手握住手柄，躯干略前倾然后拉直坐正，肩胛后缩',
    ],
    execution: [
      '吸气，略让躯干前倾一点点，感受背阔轻微拉伸',
      '呼气，将手柄向腹部/肚脐靠近位置拉近，肘沿身体两侧向后划',
      '在最高收缩位置停 1 秒，然后控制下放回起始位置',
    ],
    cues: [
      '胸口始终向前，像把胸口送给手柄',
      '想象“用背拖着手柄走”，手只是挂钩',
    ],
    breathing: '拉时呼气，回位时吸气',
    tempo: '2-1-2-0',
    rangeOfMotion: '拉到手柄接近腹部，肩胛有明显夹紧感，再控制回到起始被拉伸位置',
    commonMistakes: [
      '身体大幅前后摇摆借力',
      '含胸塌背',
      '耸肩，斜方肌代偿明显',
    ],
    safetyTips: [
      '避免用过大重量“猛拉猛甩”，尤其是有腰背问题的人',
    ],
    regressions: [],
    progressions: ['row_barbell_bent_over'],
    recommendedRepRange: [
      { goal: 'hypertrophy', reps: [8, 15] },
    ],
    recommendedSets: [
      { level: 'beginner', sets: [2, 3] },
      { level: 'intermediate', sets: [3, 4] },
      { level: 'advanced', sets: [3, 5] },
    ],
    weeklyFrequency: '每周 2~3 次背部训练中均可作为中后段补充',
    notesForWho: {
      recommendedFor: ['背部新手，器械条件较好的健身房用户'],
      avoidIf: ['急性腰背疼痛时倾斜姿势都难以保持者'],
    },
    media: {
      coverImage: '/media/training/row_cable_seated.png',
    },
  }),
  baseExercise({
    id: 'face_pull_cable',
    name: '拉力器面拉',
    aliases: ['面拉'],
    bodyPart: 'back',
    subPart: 'rear_delts_upper_back',
    difficulty: 'beginner',
    equipment: ['cable'],
    isUnilateral: false,
    primaryMuscles: ['后束三角肌', '下斜方肌'],
    secondaryMuscles: ['菱形肌', '肩袖肌群'],
    movementPattern: 'horizontal_pull',
    setup: [
      '将拉力器滑轮调到头顶或略高位置，连接绳索手柄',
      '双手握住绳索两端，掌心相对，退后几步让绳索有张力',
      '站立时躯干略微后倾，核心收紧',
    ],
    execution: [
      '吸气，略让肩胛外展感受拉伸',
      '呼气，向脸的两侧拉绳索终点（大致鼻子或额头高度），同时手肘向外打开',
      '在最高点刻意挤压肩胛骨，感受上背和后束三角肌发力',
      '控制下放回到起始位置，保持全程张力',
    ],
    cues: [
      '想象朝两侧“拆开”绳索，而不是往胸前拉',
      '耳朵远离肩膀，不要耸肩',
    ],
    breathing: '拉时呼气，回放时吸气',
    tempo: '2-1-2-0',
    rangeOfMotion: '从手臂基本伸直到手柄接近脸两侧，肩关节后伸外展',
    commonMistakes: [
      '用腰猛拉，身体大幅后仰',
      '只拉到嘴巴或下巴以下，后束参与不充分',
    ],
    safetyTips: [
      '选择中小重量，优先保证动作路径和感受目标肌群',
    ],
    regressions: [],
    progressions: [],
    recommendedRepRange: [
      { goal: 'hypertrophy', reps: [12, 20] },
    ],
    recommendedSets: [
      { level: 'beginner', sets: [2, 3] },
      { level: 'intermediate', sets: [3, 4] },
      { level: 'advanced', sets: [3, 5] },
    ],
    weeklyFrequency: '建议几乎每次上肢训练都可以安排 2~4 组，有助于平衡体态',
    notesForWho: {
      recommendedFor: ['长期久坐含胸、圆肩的人', '推拉动作较多的训练者'],
      avoidIf: ['肩关节外展外旋即刻疼痛者'],
    },
    media: {
      coverImage: '/media/training/face_pull_cable.png',
    },
  }),

  // ========= 更多手臂（肱三头） =========
  baseExercise({
    id: 'triceps_pushdown_cable',
    name: '绳索下压',
    aliases: ['三头下压'],
    bodyPart: 'arms',
    subPart: 'triceps',
    difficulty: 'beginner',
    equipment: ['cable'],
    isUnilateral: false,
    primaryMuscles: ['肱三头肌'],
    secondaryMuscles: [],
    movementPattern: 'elbow_extension',
    setup: [
      '站在高位拉力器前，连接绳索或直杆手柄',
      '双手握住手柄，肘部靠近身体两侧，前臂大致竖直',
      '躯干略前倾，核心收紧，肩膀放松下沉',
    ],
    execution: [
      '吸气，保持上臂稳定不动',
      '呼气，伸肘将手柄向下压至肘几乎完全伸直位置',
      '在最低点短暂停顿，感受肱三头肌后侧发力',
      '控制回到起始位置，避免手柄被拉力器弹回',
    ],
    cues: [
      '肘像“铰链”，只让前臂转动',
      '肩膀不要跟着上下抬起',
    ],
    breathing: '下压时呼气，回升时吸气',
    tempo: '2-0-2-0',
    rangeOfMotion: '从前臂略高于水平到完全伸直，但不过度锁死肘关节',
    commonMistakes: [
      '上臂前后大幅摆动，变成肩部参与较多',
      '身体前后晃动借力',
    ],
    safetyTips: [
      '肘关节已有疼痛史者要注意减小重量与次数',
    ],
    regressions: [],
    progressions: ['triceps_dip_parallel_bar'],
    recommendedRepRange: [
      { goal: 'hypertrophy', reps: [8, 15] },
    ],
    recommendedSets: [
      { level: 'beginner', sets: [2, 3] },
      { level: 'intermediate', sets: [3, 4] },
      { level: 'advanced', sets: [3, 5] },
    ],
    weeklyFrequency: '每周 1~3 次，常放在推练或上肢练习尾段',
    notesForWho: {
      recommendedFor: ['希望增加手臂后侧线条感的人'],
      avoidIf: ['过度伸肘即刻疼痛者'],
    },
    media: {
      coverImage: '/media/training/triceps_pushdown_cable.png',
    },
  }),

  // ========= 更多核心 =========
  baseExercise({
    id: 'dead_bug',
    name: '死虫',
    aliases: [],
    bodyPart: 'core',
    subPart: 'anti_extension',
    difficulty: 'beginner',
    equipment: ['bodyweight'],
    isUnilateral: false,
    primaryMuscles: ['腹直肌', '腹横肌'],
    secondaryMuscles: ['髋屈肌群'],
    movementPattern: 'dynamic_core',
    setup: [
      '仰卧在地，双臂伸向天花板，髋膝约 90° 屈曲，大腿垂直地面，小腿与地面平行',
      '下背轻轻贴近地面，收紧腹部',
    ],
    execution: [
      '缓慢将右腿向前伸直接近地面，同时左臂向头顶方向伸直接近地面',
      '整个过程中保持下背贴地，不要塌腰',
      '回到起始姿势，换边重复（左腿+右臂）',
    ],
    cues: [
      '想象“把肋骨向骨盆收拢”，避免腰离地',
      '动作缓慢可控，不追求速度',
    ],
    breathing: '下放手脚时慢慢吸气，回到中间时呼气',
    tempo: '2-0-2-0',
    rangeOfMotion: '在腰椎能保持贴地前提下尽量伸展手脚',
    commonMistakes: [
      '为追求动作大幅度导致腰离地明显弓起',
      '用脖子和肩在地上紧绷支撑',
    ],
    safetyTips: [
      '腰椎敏感者要从较小动作幅度开始，避免下背反复弓起',
    ],
    regressions: [],
    progressions: ['dead_bug_with_band'],
    recommendedRepRange: [
      { goal: 'endurance', reps: [8, 16] }, // 每侧合计
    ],
    recommendedSets: [
      { level: 'beginner', sets: [2, 3] },
      { level: 'intermediate', sets: [3, 4] },
      { level: 'advanced', sets: [3, 4] },
    ],
    weeklyFrequency: '每周 2~4 次，常与平板支撑搭配使用',
    notesForWho: {
      recommendedFor: ['想改善核心控制、避免塌腰深蹲和硬拉的人'],
      avoidIf: ['仰卧屈髋即刻诱发下背剧烈疼痛者'],
    },
    media: {
      coverImage: '/media/training/dead_bug.png',
    },
  }),
]

